train_dataset_name: eicu_class_train
test_dataset_name: eicu_class_test
train_batch_size: 512
test_batch_size: 1024
fed_after_n_batches: 2
train_epochs: 10
metrics:
  - precision
  - recall
optimizer_params:
  lr: 0.05
  momentum: 0.9
